pipeline:

  build-branch:
    image: plugins/docker
    repo: scienta/k8s-test
    dockerfile: ./docker/Dockerfile
    context: ./
    auto_tag: false
    tags: "branch-${DRONE_BRANCH}"
    secrets: [ docker_username, docker_password ]
    when:
      event: [push]

  build-tag:
    image: plugins/docker
    repo: scienta/k8s-test
    dockerfile: ./docker/Dockerfile
    context: ./
    auto_tag: false
    tags: "${DRONE_TAG}"
    secrets: [ docker_username, docker_password ]
    when:
      event: [tag]
